### ISSUE TITLE
Login no Gist não esta pegando

### ISSUE THREAD

**Issue by minicocoxt** [itallolegal/esteno-stream#1]
Tentando logar no Gist e não esta pegando :/ n faz login

**Comment by itallolegal** [comment]
Instalou o [Git](https://git-scm.com/)?

**Comment by itallolegal** [comment]
> Tentando logar no Gist e não esta pegando :/ n faz login

Testei e realmente não está funcionando. Assim que possivel lanço uma atualização corrigindo o problema.
O jeito que o script se conecta ao gist está ultrapassado.

**Comment by minicocoxt** [comment]
Ah eu fechei pq que achei que eu era burro. Porém criei um token em https://github.com/settings/tokens e foi normalmente

**Comment by itallolegal** [comment]
> Ah eu fechei pq que achei que eu era burro. Porém criei um token em https://github.com/settings/tokens e foi normalmente

Sim, antes dava para fazer usando autenticação básica, agora é obrigatório que seja por token.

**Comment by itallolegal** [comment]
> Ah eu fechei pq que achei que eu era burro. Porém criei um token em https://github.com/settings/tokens e foi normalmente

Mais tarde eu atualizo pro script gerar ^^

**Comment by minicocoxt** [comment]
Obrigado e desculpa qualquer coisa

**Comment by itallolegal** [comment]
> Obrigado e desculpa qualquer coisa

Nah até agradeço pro avisar, tinha esquecido que o github ia mudar isso.

Vou fechar esse issue.
